name: Release (auto version from commits)

on:
    push:
        branches: [master]


permissions:
    contents: write
    pull-requests: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Release Please
              uses: google-github-actions/release-please-action@v4
              with:
                release-type: simple
                bump-minor-pre-major: true
                changelog-types: >
                    [{"type":"feat","section":"Features","hidden":false},
                    {"type":"fix","section":"Bug Fixes","hidden":false},
                    {"type":"perf","section":"Performance","hidden":false},
                    {"type":"refactor","section":"Refactors","hidden":true},
                    {"type":"docs","section":"Docs","hidden":true},
                    {"type":"style","section":"Style","hidden":true},
                    {"type":"test","section":"Tests","hidden":true},
                    {"type":"build","section":"Build System","hidden":true},
                    {"type":"ci","section":"CI","hidden":true},
                    {"type":"chore","section":"Chores","hidden":true}]

                    #feat: → MINOR, fix: → PATCH, feat!: or BREAKING CHANGE: → MAJOR.